notifications:
  email: false
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "12"
  - "13"
  - "14"

cache:
  directories:
    - $HOME/.npm
before_install:
  - echo $TRAVIS_BRANCH
  - echo `git describe --tags --always HEAD`
  - npm config set progress false
  - npm config set spin false
script:
  - npm test
