version: 1.0.{build}-{branch}

image:
  - Visual Studio 2015

build: off
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"

matrix:
  fast_finish: true

platform:
  - x64

# cache:
#   - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm config set progress false
  - npm config set spin false
  - npm install

test_script:
  - npm test